### ISSUE TITLE
any demo script?

### ISSUE THREAD

**Issue by Kenneth-X** [amazon-research/bigdetection#10]
Is there any demo script  to inference one single image and visualize?
like [https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.py](url)

**Comment by bryanyzhu** [comment]
There is a demo folder contributed in https://github.com/amazon-research/bigdetection/tree/main/demo

**Comment by Kenneth-X** [comment]
i followed the install instruction ,which is :
```
# Install Pytorch
conda install pytorch==1.8.0 torchvision==0.9.0 cudatoolkit=10.2 -c pytorch

# Install mmcv
pip install mmcv-full==1.3.9 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html

# Clone and install
git clone https://github.com/amazon-research/bigdetection.git
cd bigdetection
pip install -r requirements/build.txt
pip install -v -e .
```

but got the **error**:
```
Traceback (most recent call last):
  File "demo/image_demo.py", line 51, in <module>
    main(args)
  File "demo/image_demo.py", line 26, in main
    result = inference_detector(model, args.img)
  File "/home/xt.xie/workspace/project/dog_stroller/bigdetection/bigdetection/mmdet/apis/inference.py", line 121, in inference_detector
    test_pipeline = Compose(cfg.data.test.pipeline)
  File "/home/xt.xie/.conda/envs/mm/lib/python3.8/site-packages/mmcv/utils/config.py", line 47, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test'
```

**Comment by bryanyzhu** [comment]
@cailk @JY-Qiao Given the demo script is contributed by you, can you help? Thank you.

**Comment by sujeongkim** [comment]
Any updates? I am having the same issue with "configs/BigDetection/cbnetv2/htc_cbv2_swin_base_giou_4conv1f_adamw_bigdet.py"

**Comment by sujeongkim** [comment]
Adding "test" to the "data" dictionary in the config file ([link](https://github.com/amazon-research/bigdetection/blob/c3289adf62e7f82b7fa1523fea4ebdf99c0322ee/configs/BigDetection/cbnetv2/htc_cbv2_swin_base_giou_4conv1f_adamw_bigdet.py#L130)) seems working.

Replace lines 130-134 with this:
`data = dict(
    samples_per_gpu=samples_per_gpu,
    train=dict(
        pipeline=train_pipeline),
    test=dict(
        pipeline=test_pipeline)
)`

**Comment by cailk** [comment]
> Adding "test" to the "data" dictionary in the config file ([link](https://github.com/amazon-research/bigdetection/blob/c3289adf62e7f82b7fa1523fea4ebdf99c0322ee/configs/BigDetection/cbnetv2/htc_cbv2_swin_base_giou_4conv1f_adamw_bigdet.py#L130)) seems working.
> 
> Replace lines 130-134 with this: `data = dict( samples_per_gpu=samples_per_gpu, train=dict( pipeline=train_pipeline), test=dict( pipeline=test_pipeline) )`

Hi, sorry for the late reply! We have not met such an error in our local environment. It is great that adding a test configuration in "data" would solve this problem. Thank you for your helpful advice.
